repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]