kind: Service
apiVersion: v1
metadata:
  name: gene-saver-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  selector:
      app: gene-saver-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30007
