version: "3"

tasks:
  build-image:
    desc: builds docker image
    cmds:
      - docker build -t gene-saver-app .
  run-app:
    desc: runs vue application on port 8080
    cmds:
      - docker run -it -p 8080:80 gene-saver-app
